### ISSUE TITLE
unrecognised determinism value 'multidet'

### ISSUE THREAD

**Issue by anionic** [rla/prolog-markdown#10]
Uses 'multidet' as a determinism value in two predicate declaration headers (both in md/md_line.pl). SWI Prolog 8.0.3 (at least) complains about this, e.g.

> Invalid mode declaration in PlDoc comment: //(string_limit(-'Codes',+'Limit'))is multidet

I guess this is a typo for 'multi'?

**Comment by rla** [comment]
I fixed it and released new version of the pack.
