### ISSUE TITLE
install per directions on swi-prolog.org failing

### ISSUE THREAD

**Issue by Anniepoo** [rla/prolog-markdown#8]
pack_install('http://packs.rlaanemets.com/markdown/markdown-*.tgz')            .
% Querying "http://packs.rlaanemets.com/markdown/" to find new versions ...
ERROR: Arguments are not sufficiently instantiated
ERROR: In:
ERROR:   [13] atomic_list_concat([_G5983|_G5984],'.',_G5981)
ERROR:   [12] prolog_pack:atom_version(_G5999,version(...)) at /usr/local/lib/swipl-7.2.3/library/prolog_pack.pl:1428
ERROR:   [11] prolog_pack:download_file('http://packs.rlaanemets.com/markdown/markdown-0.0.2.tgz',markdown,_G6019,[...|...]) at /usr/local/lib/swipl-7.2.3/library/prolog_pack.pl:816
ERROR:   [10] prolog_pack:pack_install_from_url(http,'http://packs.rlaanemets.com/markdown/markdown-0.0.2.tgz','/home/anniepoo/lib/swipl/pack',markdown,[...|...]) at /usr/local/lib/swipl-7.2.3/library/prolog_pack.pl:794
ERROR:    [9] prolog_pack:pack_install(markdown,'/home/anniepoo/lib/swipl/pack',[...|...]) at /usr/local/lib/swipl-7.2.3/library/prolog_pack.pl:594
ERROR:    [8] prolog_pack:pack_install(markdown,[...|...]) at /usr/local/lib/swipl-7.2.3/library/prolog_pack.pl:535
ERROR:    [7] prolog_pack:pack_install('http://packs.rlaanemets.com/markdown/markdown-*.tgz') at /usr/local/lib/swipl-7.2.3/library/prolog_pack.pl:414
[debug]  ?- 

dropped me into the graphical debugger with uninstantiated args.

**Comment by rla** [comment]
Thanks, I will update the instructions to simply use `markdown` and push a new version. Looks like the old way of installation with version wildcard does not work anymore.

**Comment by rla** [comment]
According to documentation this should still work:

http://www.swi-prolog.org/pldoc/doc_for?object=pack_install/1

> HTTP URL of an archive file name. This URL may contain a star (*) for the version. In this case pack_install asks for the deirectory content and selects the latest version.

**Comment by rla** [comment]
Fixed in the linked SWI issue. Not releasing a workaround.
